/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Rust-backed ICARUS Harness bridge. The JavaScript CLI/TUI layer transports these values but
 * never owns the persistent policy, task, lock, or event semantics.
 */
export declare function harnessInit(repoRoot: string, agents: Array<string>): string
export declare function harnessMigrate(repoRoot: string, dryRun: boolean, agents: Array<string>): string
export declare function harnessDoctor(repoRoot: string): string
/**
 * Read and validate the repository policy in the Rust authority. The Node CLI/MCP layer may
 * display the result, but cannot parse YAML or decide whether an invalid policy is acceptable.
 */
export declare function harnessPolicyCheck(repoRoot: string): string
/**
 * Rust-derived repository identity for an optional authority transport.  Node never derives a
 * repo id from a mutable path or remote URL itself.
 */
export declare function harnessRepositoryIdentity(repoRoot: string): string
/**
 * Read a durable Rust-recorded policy denial by id. The Node layer does not recreate policy
 * reasons from current files, because current policy can differ from the decision-time state.
 */
export declare function harnessPolicyExplain(repoRoot: string, denialId: string): string
export declare function harnessStartTask(repoRoot: string, objective: string, contractJson: string): string
export declare function harnessTaskStatus(repoRoot: string, taskId: string): string
export declare function harnessStartReleaseCandidateDogfood(repoRoot: string, releaseId: string): string
export declare function harnessReleaseCandidateDogfoodReport(repoRoot: string): string
export declare function harnessAttestReleaseCandidateDogfood(repoRoot: string, approvalId: string, approver: string): string
export declare function harnessTransitionTask(repoRoot: string, taskId: string, target: string): string
export declare function harnessResumeTask(repoRoot: string, taskId: string): string
export declare function harnessPrepareRun(repoRoot: string, taskId: string, agent: string, workspaceMode: string, acknowledgeDirtyCurrent: boolean): string
export declare function harnessReconcileRun(repoRoot: string, taskId: string): string
export declare function harnessValidateAgentArguments(agent: string, argumentsJson: string): void
export declare function harnessVerifyTaskCriterion(repoRoot: string, taskId: string, criterionId: string): string
export declare function harnessAttestTaskCriterion(repoRoot: string, taskId: string, criterionId: string, approvalId: string, approver: string, expiresAt?: string | undefined | null): string
export declare function harnessSealTask(repoRoot: string, taskId: string): string
export declare function harnessExportTask(repoRoot: string, taskId: string, redacted: boolean): string
/**
 * Install a transport-authenticated authority snapshot.  JavaScript only carries the opaque
 * JSON document; Rust validates repository identity, scope, expiry, and digest before caching.
 */
export declare function harnessInstallAuthoritySnapshot(repoRoot: string, snapshotJson: string): string
export declare function harnessInstallAuthoritySnapshotWithReplacement(repoRoot: string, snapshotJson: string, acceptReplacement: boolean): string
export declare function harnessInspectAuthoritySync(repoRoot: string): string
/**
 * Build a redacted outbound bundle.  This method deliberately cannot issue an HTTP request or
 * receive a credential: network transport remains an explicit opt-in adapter boundary.
 */
export declare function harnessBuildAuthoritySyncRequest(repoRoot: string, taskId: string, scopeJson: string): string
export declare function harnessProposeSkill(repoRoot: string, skillJson: string): string
export declare function harnessEvaluateSkill(repoRoot: string, skillId: string, replayTaskId: string, baselineTaskId?: string | undefined | null): string
export declare function harnessRecordActiveSkillOutcome(repoRoot: string, skillId: string, taskId: string): string
export declare function harnessReviewActiveSkills(repoRoot: string): string
export declare function harnessPromoteSkill(repoRoot: string, skillId: string, ownerApproval?: string | undefined | null): string
export declare function harnessRetireSkill(repoRoot: string, skillId: string, reason: string, ownerApproval?: string | undefined | null): string
export declare function harnessAmendTaskContract(repoRoot: string, taskId: string, contractJson: string, reason: string, approvalId?: string | undefined | null): string
export declare function harnessCheckpointTask(repoRoot: string, taskId: string, phase: string, inputJson: string): string
export declare function harnessBuildContext(repoRoot: string, taskId: string, budgetTokens: number): string
export declare function harnessBuildContextDelta(repoRoot: string, taskId: string, checkpointSequence: number, budgetTokens: number): string
export declare function harnessRecordGraphReceipt(repoRoot: string, sourceFingerprint: string): string
/**
 * Return the authoritative graph-source fingerprint. The JavaScript graph adapter uses this
 * rather than maintaining a second hashing implementation, so the fingerprint it stores and
 * the one Rust verifies can never drift because of traversal or ordering differences.
 */
export declare function harnessGraphSourceFingerprint(repoRoot: string): string
export declare function harnessSkillAuthoringBrief(repoRoot: string, taskId: string): string
export declare function harnessAuthorizeAction(repoRoot: string, taskId: string, kind: string, path?: string | undefined | null): string
/**
 * Authorize and audit a documented Claude Edit/Write PreToolUse event. The JavaScript hook
 * adapter transports only normalized fields; Rust verifies the prepared execution and appends
 * the resulting allow/deny decision itself.
 */
export declare function harnessAuthorizeAdapterWrite(repoRoot: string, taskId: string, agent: string, toolName: string, path: string): string
/**
 * Record a typed Claude Edit/Write PostToolUse observation in the Rust audit chain. This is a
 * tool-boundary record only; it cannot substitute for an ICARUS verification receipt.
 */
export declare function harnessRecordAdapterPostAction(repoRoot: string, taskId: string, agent: string, toolName: string, path: string): string
/**
 * Bind the stable thread returned by Codex app-server to a prepared Codex execution. Node may
 * transport the response, but the native harness persists and validates the binding.
 */
export declare function harnessBindCodexAppServerThread(repoRoot: string, taskId: string, threadId: string): string
/**
 * Record a bounded structured Codex app-server notification. The native core rejects unknown
 * event vocabularies and mismatched threads rather than accepting arbitrary JSON-RPC payloads.
 */
export declare function harnessRecordCodexAppServerEvent(repoRoot: string, taskId: string, method: string, paramsJson: string): string
/**
 * Decide a Codex app-server approval request in Rust. Current decisions intentionally fail
 * closed until the protocol exposes canonical per-file write paths and a native command policy.
 */
export declare function harnessDecideCodexAppServerApproval(repoRoot: string, taskId: string, method: string, paramsJson: string): string
/**
 * Execute one governed Codex app-server turn inside the Rust native addon. This is synchronous
 * by design: JavaScript only invokes the native bridge and then performs its usual post-run
 * reconciliation; it never parses app-server events or decides an approval.
 */
export declare function harnessRunCodexAppServer(repoRoot: string, taskId: string, prompt?: string | undefined | null): string
/**
 * Hand a prepared managed execution to ICARUS verification. This does not accept an agent
 * result or seal a task; it only records the durable execution-to-verification boundary.
 */
export declare function harnessHandoffManagedTask(repoRoot: string, taskId: string): string
/**
 * Record a typed adapter process boundary observed by the local managed launcher. This bridge
 * exposes no arbitrary event payload: only Rust's bounded lifecycle receipt can enter the audit
 * chain, so a presentation client cannot turn model prose into trusted execution evidence.
 */
export declare function harnessRecordAdapterLifecycle(repoRoot: string, taskId: string, eventType: string, exitCode?: number | undefined | null): string
/** One recall hit returned to JS. */
export interface MnemeHit {
  slotId: number
  score: number
  text: string
}
/**
 * One stored record: slot id + its full-record text payload. Used by the Prisma adapter's loader
 * to hydrate every memory from `.amr` on open (Path B — `.amr` as the relational store).
 */
export interface RecordRow {
  slotId: number
  text: string
}
/**
 * One typed edge from a slot: target slot, edge type, weight. The relationship backend reads these
 * back to reconstruct relationship records from the `.amr` graph.
 */
export interface EdgeRow {
  target: number
  edgeType: number
  weight: number
}
/**
 * One page of a streaming record scan: the live records found plus the slot to resume from
 * (`next_slot` == u32::MAX when the scan is complete). Replaces all-at-once `all_records()`
 * for large shards — the caller never materializes the whole store in JS heap.
 */
export interface RecordPage {
  rows: Array<RecordRow>
  nextSlot: number
}
/**
 * A freshly generated ML-DSA-65 keypair, as raw bytes for the Node layer to persist.
 * `signing_key` is the 32-byte SEED (`SigningKey::to_seed()`/`from_seed()` — the crate's own
 * "preferred serialization... consistently 32-bytes" form), not the full expanded key —
 * smaller to store, and re-expanding from seed on load is cheap.
 */
export interface SigningKeypair {
  signingKey: Buffer
  verifyingKey: Buffer
}
export declare function generateSigningKeypair(): SigningKeypair
/**
 * Sign arbitrary bytes with a raw 32-byte signing-key seed (from
 * `generate_signing_keypair`). The CALLER builds the canonical payload (slot id + text,
 * etc.) — this function only does the cryptographic operation, so the exact bytes being
 * signed are never ambiguous from reading this file alone.
 */
export declare function signBytes(signingKeySeed: Buffer, payload: Buffer): Buffer
/**
 * Verify `signature` over `payload` against a raw verifying-key encoding. Returns `false`
 * for a bad signature or tampered payload, NOT an error — only a malformed key/signature
 * (wrong length, can't even be parsed) is an error. A caller checking "is this memory
 * authentic" wants a clean boolean for the common tamper case, not exception-handling for it.
 */
export declare function verifyBytes(verifyingKeyBytes: Buffer, payload: Buffer, signature: Buffer): boolean
export interface AuditKeypair {
  signingKey: Buffer
  verifyingKey: Buffer
}
export declare function generateAuditKeypair(): AuditKeypair
export declare function auditSignBytes(signingKeyBytes: Buffer, payload: Buffer): Buffer
export declare function auditVerifyBytes(verifyingKeyBytes: Buffer, payload: Buffer, signature: Buffer): boolean
/**
 * A per-org mneme store (wraps one `.amr` shard).
 *
 * Holds a native id→slot index (u64 hash of the record's JSON `id` → candidate slots) so JS
 * never needs an in-heap Map of every record — the index costs ~24 bytes/record in Rust
 * (no GC pressure) vs ~1-2KB/record for parsed JS objects, which was the scale wall.
 */
export declare class MnemeStore {
  /**
   * Open (or create) the shard for `org_id` under `data_root` with embedding dimension `dim`.
   * Builds the id→slot index with one mmap scan of live slots.
   */
  static open(dataRoot: string, orgId: string, dim: number): MnemeStore
  /**
   * Insert a memory (text + embedding). `valid_from` is nanoseconds (0 = unspecified).
   * Returns the stable slot id.
   */
  insert(text: string, vector: Float32Array, validFrom: number): number
  /**
   * Insert tagged with a layer (0=memory, 1=evidence, 2=cognitive). Lets one shard hold all 3
   * HIVEMIND layers, separated, for layer-filtered recall.
   */
  insertLayered(text: string, vector: Float32Array, validFrom: number, layer: number): number
  /** Build the HNSW overlay over all current vectors (call after a bulk load). */
  enableHnsw(): void
  /**
   * Train this shard's PQ (Product Quantization) codebook and encode every live vector into
   * its compact `vector_pq` code, enabling `recall_pq()`. Deterministic given `seed` (same
   * seed -> same codebook -> same recall_pq results, useful for reproducible tests). This is
   * the ONLY way to make `pq_trained()` true / `recall_pq()` usable — there is no implicit
   * auto-train, so a caller always knows exactly when the (real, one-time) training cost was
   * paid. Blocks the event loop for its duration (k-means over every live vector) — like
   * `enable_hnsw()`/`compact()`, call it after a bulk load or from a background job, not on a
   * per-request path. Safe to call again later (e.g. after significant growth) to retrain.
   */
  trainPq(seed: number): void
  /** True if `train_pq()` has run at least once for this shard. */
  pqTrained(): boolean
  /**
   * PQ/ADC-backed recall — an alternative to `recall()`'s HNSW/brute path with a different
   * tradeoff: fast to build always, fast to QUERY only at small/medium shard sizes (measured
   * on real bge-m3 data: at 10k vectors it beats HNSW on both build time and query latency at
   * equal recall; at 100k it still builds ~6x faster but queries ~3x slower than HNSW at
   * equal recall — PQ stays O(n) per query with a cheap per-item cost, HNSW's near-O(log n)
   * traversal wins as the shard grows). Good fit: shards you rebuild often (dev/test, small
   * orgs, frequently-retrained data) where build time matters more than the last few ms of
   * query latency. NOT a drop-in replacement for `recall()` at real scale — measure your own
   * shard size before choosing this over HNSW.
   *
   * FAILS CLOSED, not silently wrong: throws a clear error if `train_pq()` hasn't run yet,
   * rather than falling back to some other path a caller didn't ask for — a correctness
   * primitive should never guess which search the caller wanted.
   */
  recallPq(query: Float32Array, topK: number): Array<MnemeHit>
  /** Recall the top-`top_k` memories for `query`. */
  recall(query: Float32Array, topK: number): Array<MnemeHit>
  /**
   * Layer-filtered recall: `layer` 0=memory, 1=evidence, 2=cognitive; pass -1 for all layers.
   * This is how the 3 layers are queried separately from one shard (recall=memory,
   * provenance=evidence, synthesis=cognitive), exactly like a Qdrant `layer` filter.
   */
  recallLayer(query: Float32Array, topK: number, layer: number): Array<MnemeHit>
  /**
   * Add a typed edge `slot_id` --(edge_type)--> `target` (unbounded; overflows to `.edg`).
   * edge_type: 1=Mentions 2=Updates 3=Derives 4=Contradicts 5=PartOf 6=Extends.
   */
  addEdge(slotId: number, target: number, edgeType: number, weight: number): void
  /**
   * Typed graph traversal from `seed`, following ONLY `edge_type`, up to `max_hops`. Returns
   * reachable slot ids (HIVEMIND `traverse_graph` parity, served from the one shard).
   */
  traverseTyped(seed: number, edgeType: number, maxHops: number): Array<number>
  /**
   * Bi-temporal point-in-time: the version of a memory current as of transaction time
   * `txn_time` (ns), walking the Updates chain from `head_slot`. Returns the slot id, or -1 if
   * not yet known (HIVEMIND `hivemind_at` / `timeline` parity).
   */
  asOf(headSlot: number, txnTime: number): number
  /**
   * Insert with explicit bi-temporal stamps: `created_at` (transaction time — when learned)
   * and `valid_from` (valid time — when true), both ns. `created_at` drives `as_of`.
   */
  insertAt(text: string, vector: Float32Array, createdAt: number, validFrom: number): number
  /**
   * Update memory `old_slot` with a new version: inserts, auto-links new--Updates-->old, marks
   * old superseded. Recall then returns only the latest; `as_of` reaches the history. `created_at`
   * is the transaction time of the new version (drives `as_of`). Returns the new slot id.
   */
  update(oldSlot: number, text: string, vector: Float32Array, createdAt: number, validFrom: number): number
  /** Delete (tombstone) a memory by slot id. */
  delete(slotId: number): void
  /**
   * Rewrite a live slot's record TEXT in place (vector/layer/temporal/edges untouched) —
   * the durability primitive for metadata-only mutations (tags, recall reinforcement,
   * is_latest supersession flips). Old text bytes are reclaimed by `compact()`.
   */
  rewriteText(slotId: number, text: string): void
  /**
   * Resolve a record's JSON `id` to its live slot, or -1. Served from the native id index
   * (hash → candidate slots, exact-verified against slot text) — O(1), no JS-side Map needed.
   */
  findById(id: string): number
  /** Read one live slot's record text. `Err` for tombstoned/never-used slots. */
  slotText(slotId: number): string
  /**
   * Streaming record scan: up to `limit` live records starting at slot `from_slot`, plus the
   * slot to resume from (u32::MAX when done). O(page) JS heap instead of O(shard).
   */
  recordsPage(fromSlot: number, limit: number): RecordPage
  /**
   * Native BM25 lexical search over every live record's stored text. Full corpus-wide
   * document-frequency/IDF statistics (see `bm25.rs`), not a substring or prefix heuristic --
   * this is the engine's first lexical search of any kind. `MnemeStore` previously had vector
   * recall, graph edges, and temporal operations, and nothing that scored on TEXT at all.
   *
   * KNOWN LIMITATION, STATED RATHER THAN HIDDEN: `Hit` does not currently surface a record's
   * layer, so this scans every live slot regardless of the 0/1/2 layer used by
   * `insert_layered`/`recall_layer`. A caller needing "evidence only" or "memory only" lexical
   * search must filter the returned ids against a layer lookup of its own for now; adding a
   * layer to `Hit` (or a native filtered variant) is the natural follow-up, not done here.
   *
   * O(shard) per call: two passes over every live record (corpus stats, then scoring), same
   * cost shape as the JS-side scan-based lexical lanes this engine's callers already use in
   * production. A persistent postings index for O(matching-docs) query cost at very large
   * corpora is a further step, not this one.
   */
  bm25Search(query: string, topK: number): Array<MnemeHit>
  /** Number of live memories in the shard. */
  liveCount(): number
  /** Read a slot's typed edges (target, type, weight) — for reconstructing relationship records. */
  slotEdges(slot: number): Array<EdgeRow>
  /**
   * Scan every live slot and return its (slot_id, full-record text). The Prisma adapter calls
   * this once on open to hydrate all records from `.amr` — making `.amr` the relational store.
   */
  allRecords(): Array<RecordRow>
  /**
   * Compact the text region, reclaiming bytes of deleted memories. Returns bytes reclaimed.
   * A maintenance op — run when the shard is idle.
   */
  compact(): number
  /** Flush to disk. */
  flush(): void
}
