/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** One recall hit returned to JS. */
export interface MnemeHit {
  slotId: number
  score: number
  text: string
}
/** A per-org mneme store (wraps one `.mseg` shard). */
export declare class MnemeStore {
  /** Open (or create) the shard for `org_id` under `data_root` with embedding dimension `dim`. */
  static open(dataRoot: string, orgId: string, dim: number): MnemeStore
  /**
   * Insert a memory (text + embedding). `valid_from` is nanoseconds (0 = unspecified).
   * Returns the stable slot id.
   */
  insert(text: string, vector: Float32Array, validFrom: number): number
  /** Build the HNSW overlay over all current vectors (call after a bulk load). */
  enableHnsw(): void
  /** Recall the top-`top_k` memories for `query`. */
  recall(query: Float32Array, topK: number): Array<MnemeHit>
  /** Delete (tombstone) a memory by slot id. */
  delete(slotId: number): void
  /** Number of live memories in the shard. */
  liveCount(): number
  /**
   * Compact the text region, reclaiming bytes of deleted memories. Returns bytes reclaimed.
   * A maintenance op — run when the shard is idle.
   */
  compact(): number
  /** Flush to disk. */
  flush(): void
}

// --- JS wrapper (index.js) ---------------------------------------------------

export interface QdrantPoint {
  id: string | number
  vector: number[] | Float32Array
  payload?: Record<string, unknown>
}

export interface SearchHit {
  id: string | number
  score: number
  payload: Record<string, unknown>
}

/** Drop-in replacement for HIVEMIND's QdrantVectorStore (one shard per collection). */
export declare class MnemeVectorStore {
  constructor(opts?: { dataRoot?: string; dim?: number })
  upsert(collectionName: string, points: QdrantPoint[]): Promise<{ upserted: number }>
  search(collectionName: string, vector: number[] | Float32Array, topK?: number): Promise<SearchHit[]>
}

export declare function sanitizeOrg(name: string): string
